### ISSUE TITLE
Grails Runtime Exception - no available templates in a fresh install on CentOS 7.1

### ISSUE THREAD

**Issue by fsando** [PhenotypeFoundation/PhenotypeDatabase#144]
I installed dbNp on CentOS 7.1
I did not install the apache proxy yet - as I want to see it function before I go on.

The installation appear to work as expected - until I try to select template:
The same error happens if I try to "browse/edit" any of the template submenus.

Steps to reproduce:
1) log in (as default admin or default user)
2) select create > create a new study
3) there are no available templates in the drop down menu, so select "add / modify..."

Expected result: 
some menu to select templates 

Actual result:

Grails Runtime Exception
Error Details
Error 500: Error processing GroovyPageView: Cannot get property 'entity' on null object
Servlet: grails
URI: /gscf/grails/templateEditor.dispatch
Exception Message: Error processing GroovyPageView: Cannot get property 'entity' on null object
Caused by: Error processing GroovyPageView: Cannot get property 'entity' on null object
Class: gsp_gdt_templateEditorindex_gsp
At Line: [60]
Code Snippet:
Stack Trace

org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Cannot get property 'entity' on null object
    at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
    at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
    at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Cannot get property 'entity' on null object
    at gsp_gdt_templateEditorindex_gsp$_run_closure2.doCall(gsp_gdt_templateEditorindex_gsp.groovy:88)
    at gsp_gdt_templateEditorindex_gsp.run(gsp_gdt_templateEditorindex_gsp.groovy:141)
    ... 6 more

**Comment by FerryJagers** [comment]
Fixed in ff71fab00aeec9f9b8a608ba681101a542a70734
